input {
    kb_layout = us
    numlock_by_default = false
    repeat_delay = 250
    repeat_rate = 35
    accel_profile = flat

    focus_on_close = 1

    touchpad {
        natural_scroll = true
        disable_while_typing = $touchpadDisableTyping
        scroll_factor = $touchpadScrollFactor
    }
}

device {
    name = asue140d:00-04f3:31b9-touchpad
    sensitivity = 1.5
}

binds {
    scroll_event_delay = 0
}

cursor {
    hotspot_padding = 1
}

