# ############# Nvidia #############
# See https://wiki.hyprland.org/Nvidia/

env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# May cause crashes in Firefox — remove if so
env = GBM_BACKEND,nvidia-drm

# Hardware video acceleration — requires libva-nvidia-driver package
# env = NVD_BACKEND,direct

cursor {
    no_hardware_cursors = true
}
