scrolling {
    fullscreen_on_one_column = true
    focus_fit_method = 1
    column_width = 0.5
    follow_focus = true
    follow_min_visible = 0.0
    explicit_column_widths = 0.35, 0.5, 0.65, 1.0
}

####- Uncommenting lines here will effect how your workspaces behave. -###
#   Here you will find default controls for hyprscrolling which is different than tiling.
#   Scrolling will make your workspace infinite and will open windows next to eachother.
#   Not all windows will may be displayed at the same time.



####- Uncomment each for each workspace you want to be a scrolling workspace -###

#workspace = 1, layout:scrolling,layoutopt:direction:left ###- you can also change the direction of scroll.
#workspace = 2, layout:scrolling,layoutopt:direction:left ###- options are: up, down, left, right
#workspace = 3, layout:scrolling,layoutopt:direction:left
#workspace = 4, layout:scrolling,layoutopt:direction:left
#workspace = 5, layout:scrolling,layoutopt:direction:left
#workspace = 6, layout:scrolling,layoutopt:direction:left
#workspace = 7, layout:scrolling,layoutopt:direction:left
#workspace = 8, layout:scrolling,layoutopt:direction:left
#workspace = 9, layout:scrolling,layoutopt:direction:left
#workspace = 10, layout:scrolling,layoutopt:direction:left

####- Special workspaces can also scroll.

#workspace = special:special, layout:scrolling,layoutopt:direction:right
#workspace = special:music, layout:scrolling,layoutopt:direction:right
#workspace = special:communication, layout:scrolling,layoutopt:direction:right
#workspace = special:todo, layout:scrolling,layoutopt:direction:right

####- these keybinds may interupt existing binds and should be reviewed prior to uncommenting

#bind = Super, right, layoutmsg, move +col
#bind = Super, left, layoutmsg, move -col
#bind = Super+Shift, right, layoutmsg, swapcol r
#bind = Super+Shift, left, layoutmsg, swapcol l
#bind = Super+Shift, F, layoutmsg, focus
#bind = Super+Shift, X, layoutmsg, fit active
